// Store category list items in objects
    /// Reasoning behind decision -- most items in the list will typically remain the same, therefore data will NOT
    /// change significantly over time.

const data = {
    "clothes": [
        'underwear',
        'socks/stockings',
        'undershirts/bras',
        'sleepwear',
        'shirts',
        'dress shirts',
        'casual shirts',
        'jeans',
        'pants',
        'shorts',
        'dresses',
        'skirts',
        'sweaters/sweatshirts',
        'formal wear',
        'swimsuits/cover-ups',
        'coats/jackets/rainwear',
        'hats',
        'gloves',
        'scarves',
        'umbrella',
        'laundry kit',
        'laundry bag',
        'casual shoes',
        'hiking/athletic shoes',
        'walking shoes',
        'dress shoes',
        'sandals/flip flops',
        'belts',
        'ties',
        'jewelry (non-valuable)',
        'purses',
        'collapsible totes',
        'under clothing document holders'
    ],
    "toiletries": [
        'toothbrush',
        'toothpaste',
        'floss',
        'soap',
        'deodorant',
        'shampoo/conditioner',
        'brush/comb',
        'hairstyling tools',
        'face cleanser',
        'face moisturizer/tonic/serum',
        'sunscreen',
        'moisturizer',
        'contact lenses/solution',
        'shaving kit',
        'make-up/remover',
        'feminine products',
        'birth control',
        'nail file/clippers',
        'tweezers',
        'hand sanitizer',
        'bandages',
        'first aid ointment',
        'insect repellent',
        'medications',
        'pain relievers',
        'vitamins'
    ],
    "miscellaneous": [
        'laptop/tablet/game device',
        'chargers',
        'plug adaptor',
        'binoculars',
        'list of medications',
        'emergency contacts',
        'credit card, bank contacts',
        'passport, credit card copies'
    ],
    "carryon": [
        'mobile',
        'books/eBooks',
        'earbuds/headphones',
        'shawl/light blanket',
        'travel pillow',
        'ear plugs/eye mask',
        'tissues',
        'lip balm',
        'change of clothes',
        'food/snacks/gum',
        'in-flight medications',
        'valuables',
        'camera/memory card',
        'passport/visa/id',
        'paper/pen',
        'cash',
        'atm/credit cards',
        'health/travel insurance',
        'itinerary',
        'maps/directions',
        'guide books',
        'address book',
        'house/car keys',
        'jewelry (valuable)'
    ]
};

export default data;



